spring.application.name=NewCommerce
server.port=8083

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

razorpay.key.id=test_key
razorpay.key.secret=test_key

jwt.secret=jwt.secret=mysecretkey123456789
jwt.expiration=86400000

spring.web.cors.allowed-origins=*